INSERT INTO CUSTOMER VALUES (1, 'Kane', 'Williamson');
INSERT INTO CUSTOMER VALUES (2, 'Steve', 'Waugh');
INSERT INTO CUSTOMER VALUES (3, 'Joe', 'Root');

INSERT INTO ADDRESS(ADDRESS_ID, HOUSE_NUMBER, STREET_NAME, CITY, POST_CODE, CUSTOMER_ID) VALUES (1, '12', 'HILMANTON', 'READING', 'RG4 4UG', 1);
INSERT INTO ADDRESS(ADDRESS_ID, HOUSE_NUMBER, STREET_NAME, CITY, POST_CODE, CUSTOMER_ID) VALUES (2, '22', 'BEECH LANE', 'READING', 'RG5 4AB', 1);

INSERT INTO ADDRESS(ADDRESS_ID, HOUSE_NUMBER, STREET_NAME, CITY, POST_CODE, CUSTOMER_ID) VALUES (3, '12', 'HILMANTON', 'READING', 'RG5 4UG', 2);
INSERT INTO ADDRESS(ADDRESS_ID, HOUSE_NUMBER, STREET_NAME, CITY, POST_CODE, CUSTOMER_ID) VALUES (4, '22', 'BEECH LANE', 'READING', 'RG7 4AB', 3);
